application: checkbook
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Media
  static_dir: Media

- url: /userpage
  script: Checkbook.app

- url: /about
  script: Checkbook.app

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: Checkbook.app
  #login: required

libraries:
- name: jinja2
  version: latest

